import Link from "next/link";
import { notFound } from "next/navigation";
import { db } from "@/lib/db";
import { formatDate, getAgreementStatus, LEVEL_COLORS, cn } from "@/lib/utils";
import { ArrowLeft, MapPin, Globe2, Mail, Phone, ExternalLink, FileText, Activity, Calendar, CheckCircle2, AlertCircle, Building2, PencilLine, Users } from "lucide-react";

export const dynamic = "force-dynamic";

async function getPartner(slug: string) {
  return db.partner.findUnique({ where: { slug, status: "APPROVED" }, include: { cooperationFields: { include: { cooperationField: true } }, agreements: { orderBy: { endDate: "desc" } }, activities: { where: { status: "APPROVED" }, orderBy: { dateStart: "desc" }, include: { lecturers: { orderBy: { order: "asc" } }, students: { orderBy: { order: "asc" } } } } } });
}

export default async function PartnerDetailPage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params;
  const partner = await getPartner(slug);
  if (!partner) notFound();
  const now = new Date();
  const sixMonthsAgo = new Date(now); sixMonthsAgo.setMonth(now.getMonth() - 6);
  const recent = partner.activities.filter(a => a.dateStart && a.dateStart >= sixMonthsAgo).length > 0;
  const utilization = recent ? { label: "Sudah ada Implementasi", color: "emerald" } : { label: partner.agreements.length ? "Belum ada Implementasi" : "Potensial", color: partner.agreements.length ? "amber" : "blue" };
  const location = [partner.city, partner.country].filter(Boolean).join(", ");
  const completeness = [partner.name, partner.category, partner.address, partner.email, partner.picName, partner.agreements.length > 0, partner.activities.length > 0].filter(Boolean).length;
  const score = Math.round((completeness / 7) * 100);

  return (
    <div className="bg-stone-50"><div className="mx-auto max-w-5xl px-4 py-8 sm:py-12">
      <Link href="/mitra" className="mb-6 inline-flex items-center gap-2 text-sm font-medium text-stone-500 hover:text-emerald-700"><ArrowLeft className="h-4 w-4" /> Kembali ke daftar mitra</Link>
      <header className="rounded-2xl border border-stone-100 bg-white p-6 shadow-sm sm:p-8"><div className="flex flex-col gap-5 sm:flex-row sm:items-start sm:justify-between"><div><div className="mb-3 flex flex-wrap gap-2"><span className={cn("rounded-full border px-2.5 py-1 text-xs font-semibold", LEVEL_COLORS[partner.level] || LEVEL_COLORS.LOKAL)}>{partner.level}</span>{partner.category && <span className="rounded-full bg-stone-100 px-2.5 py-1 text-xs font-medium text-stone-600">{partner.category}</span>}<span className={cn("rounded-full px-2.5 py-1 text-xs font-semibold", utilization.color === "emerald" ? "bg-emerald-50 text-emerald-700" : utilization.color === "amber" ? "bg-amber-50 text-amber-700" : "bg-blue-50 text-blue-700")}>{utilization.label}</span></div><h1 className="text-2xl font-bold tracking-tight text-stone-900 sm:text-3xl">{partner.name}</h1>{location && <p className="mt-2 flex items-center gap-1.5 text-sm text-stone-500"><MapPin className="h-4 w-4" /> {location}</p>}</div><div className="flex flex-col items-stretch gap-3 sm:flex-row sm:items-center"><div className="rounded-xl bg-stone-50 px-4 py-3 text-center"><p className="text-2xl font-bold text-emerald-700">{score}%</p><p className="text-xs text-stone-500">Kelengkapan data</p></div><Link href={`/mitra/${partner.slug}/edit`} className="inline-flex items-center justify-center gap-1.5 rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-xs font-semibold text-emerald-700 transition-colors hover:bg-emerald-100"><PencilLine className="h-3.5 w-3.5" /> Usulkan Perbaikan Data</Link></div></div></header>

      <div className="mt-6 grid gap-6 lg:grid-cols-3"><div className="space-y-6 lg:col-span-2">
        <section className="rounded-2xl border border-stone-100 bg-white p-6 shadow-sm"><h2 className="mb-5 flex items-center gap-2 font-bold text-stone-900"><Building2 className="h-5 w-5 text-emerald-600" /> Informasi Mitra</h2><div className="grid gap-x-6 gap-y-5 sm:grid-cols-2"><Info label="Alamat" value={partner.address} icon={MapPin} /><Info label="Telepon" value={partner.phone} icon={Phone} /><Info label="Email" value={partner.email} icon={Mail} /><Info label="Website" value={partner.website} icon={Globe2} link={partner.website} /><Info label="PIC Mitra" value={partner.picName} /><Info label="Jabatan PIC" value={partner.picPosition} /></div></section>
        <section className="rounded-2xl border border-stone-100 bg-white p-6 shadow-sm"><h2 className="mb-5 flex items-center gap-2 font-bold text-stone-900"><FileText className="h-5 w-5 text-emerald-600" /> Perjanjian Kerja Sama</h2>{partner.agreements.length ? <div className="space-y-3">{partner.agreements.map(a => { const st = getAgreementStatus(a.endDate); return <div key={a.id} className="rounded-xl border border-stone-100 bg-stone-50/60 p-4"><div className="flex flex-wrap items-start justify-between gap-2"><div><p className="font-semibold text-stone-900">{a.type}{a.number ? ` · ${a.number}` : ""}</p><p className="mt-1 text-sm text-stone-500">{formatDate(a.startDate)} — {formatDate(a.endDate)}</p></div><span className={cn("rounded-full px-2.5 py-1 text-xs font-semibold", st.color === "green" ? "bg-emerald-50 text-emerald-700" : st.color === "orange" ? "bg-orange-50 text-orange-700" : st.color === "red" ? "bg-red-50 text-red-700" : "bg-amber-50 text-amber-700")}>{st.label}{st.daysLeft !== null && st.daysLeft >= 0 ? ` · ${st.daysLeft} hari` : ""}</span></div></div>})}</div> : <Empty icon={FileText} text="Belum ada data perjanjian" />}</section>
        <section className="rounded-2xl border border-stone-100 bg-white p-6 shadow-sm"><h2 className="mb-5 flex items-center gap-2 font-bold text-stone-900"><Activity className="h-5 w-5 text-emerald-600" /> Kegiatan yang Pernah Dilakukan <span className="ml-auto rounded-full bg-emerald-50 px-2.5 py-1 text-xs font-bold text-emerald-700">{partner.activities.length}</span></h2>{partner.activities.length ? <div className="space-y-4">{partner.activities.map(a => <div key={a.id} className="border-l-2 border-emerald-200 pl-4"><h3 className="font-semibold text-stone-900">{a.title}</h3><p className="mt-1 flex flex-wrap gap-3 text-xs text-stone-500"><span className="inline-flex items-center gap-1"><Calendar className="h-3.5 w-3.5" /> {formatDate(a.dateStart)}</span><span className="rounded bg-emerald-50 px-2 py-0.5 font-medium text-emerald-700">{a.type}</span></p>{a.description && <p className="mt-2 text-sm leading-relaxed text-stone-600">{a.description}</p>}{(Boolean(a.internalPic) || Boolean(a.partnerPic) || a.lecturers.length > 0 || a.students.length > 0) && <div className="mt-3 space-y-1.5 rounded-lg bg-stone-50 p-3 text-xs text-stone-600">{a.lecturers.length ? <p><span className="font-semibold text-stone-700">Pelaksana dosen:</span> {a.lecturers.map(l => `${l.name}${l.isLeader ? " (Ketua)" : ""}`).join(", ")}</p> : a.internalPic && <p><span className="font-semibold text-stone-700">PIC internal:</span> {a.internalPic}</p>}{a.students.length > 0 && <p className="flex items-start gap-1.5"><Users className="mt-0.5 h-3.5 w-3.5 shrink-0 text-stone-400" /><span><span className="font-semibold text-stone-700">Mahasiswa terlibat:</span> {a.students.map(s => s.name).join(", ")}</span></p>}{a.partnerPic && <p><span className="font-semibold text-stone-700">PIC mitra:</span> {a.partnerPic}</p>}</div>}</div>)}</div> : <Empty icon={Activity} text="Belum ada kegiatan terdokumentasi" />}</section>
      </div><aside className="space-y-6"><section className="rounded-2xl border border-stone-100 bg-white p-6 shadow-sm"><h2 className="mb-4 font-bold text-stone-900">Ringkasan Implementasi</h2><div className="space-y-4"><Metric label="Total kegiatan" value={partner.activities.length.toString()} /><Metric label="Bidang kolaborasi" value={partner.cooperationFields.length.toString()} /><Metric label="Kegiatan 6 bulan terakhir" value={partner.activities.filter(a => a.dateStart && a.dateStart >= sixMonthsAgo).length.toString()} /></div></section><section className="rounded-2xl border border-stone-100 bg-white p-6 shadow-sm"><h2 className="mb-4 font-bold text-stone-900">Bidang Kerja Sama</h2>{partner.cooperationFields.length ? <div className="flex flex-wrap gap-2">{partner.cooperationFields.map(f => <span key={f.cooperationFieldId} className="rounded-lg bg-emerald-50 px-3 py-1.5 text-xs font-medium text-emerald-700">{f.cooperationField.name}</span>)}</div> : <p className="text-sm text-stone-400">Belum ada bidang tercatat.</p>}</section><section className="rounded-2xl border border-emerald-100 bg-emerald-50/50 p-6"><p className="text-sm font-semibold text-emerald-900">Punya kegiatan bersama mitra ini?</p><p className="mt-1 text-xs leading-relaxed text-emerald-700">Bantu lengkapi dokumentasi kolaborasi Taskforce.</p><Link href="/kegiatan" className="mt-4 inline-flex w-full items-center justify-center rounded-lg bg-emerald-700 px-3 py-2.5 text-xs font-semibold text-white hover:bg-emerald-800">+ Laporkan Kegiatan</Link></section></aside></div>
    </div></div>
  );
}

function Info({ label, value, icon: Icon, link }: { label: string; value: string | null; icon?: typeof MapPin; link?: string | null }) { return <div><p className="text-xs font-medium uppercase tracking-wide text-stone-400">{label}</p>{value ? <p className="mt-1 flex items-start gap-1.5 text-sm text-stone-700">{Icon && <Icon className="mt-0.5 h-3.5 w-3.5 shrink-0 text-stone-400" />}{link ? <a href={link} target="_blank" rel="noreferrer" className="break-all text-emerald-700 hover:underline">{value}</a> : <span className="break-words">{value}</span>}</p> : <p className="mt-1 text-sm text-stone-300">Belum diisi</p>}</div> }
function Metric({ label, value }: { label: string; value: string }) { return <div className="flex items-center justify-between border-b border-stone-100 pb-3 last:border-0 last:pb-0"><span className="text-sm text-stone-500">{label}</span><span className="text-lg font-bold text-stone-900">{value}</span></div> }
function Empty({ icon: Icon, text }: { icon: typeof FileText; text: string }) { return <div className="py-6 text-center"><Icon className="mx-auto h-7 w-7 text-stone-300" /><p className="mt-2 text-sm text-stone-400">{text}</p></div> }
