"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { ArrowLeft, AlertCircle, CheckCircle2, Send, Activity, Plus, Trash2, ImagePlus, X } from "lucide-react";

interface Partner { id: string; name: string; level: string }
interface Lecturer { name: string; isLeader: boolean }

export default function LaporkanPage() {
  const [partners, setPartners] = useState<Partner[]>([]);
  const [lecturers, setLecturers] = useState<Lecturer[]>([{ name: "", isLeader: true }]);
  const [students, setStudents] = useState<string[]>([""]);
  const [form, setForm] = useState({ partnerId: "", title: "", type: "MAGANG", dateStart: "", dateEnd: "", location: "", description: "", output: "", internalPic: "", partnerPic: "", unit: "", participants: "", driveUrl: "", publicationUrl: "", submittedBy: "", submittedEmail: "" });
  const [state, setState] = useState<"idle" | "loading" | "success" | "error">("idle"); const [message, setMessage] = useState("");
  const [photoUrl, setPhotoUrl] = useState(""); const [uploading, setUploading] = useState(false);
  useEffect(() => { fetch("/api/admin/partners").then(r => r.json()).then(d => setPartners(d.partners || [])); }, []);
  const set = (key: keyof typeof form, value: string) => setForm(p => ({ ...p, [key]: value }));
  function updateLecturer(index: number, key: keyof Lecturer, value: string | boolean) { setLecturers(items => items.map((item, i) => i === index ? { ...item, [key]: value } : key === "isLeader" && value ? { ...item, isLeader: false } : item)); }
  function addLecturer() { setLecturers(items => [...items, { name: "", isLeader: false }]); }
  function addStudent() { setStudents(items => [...items, ""]); }
  async function uploadPhoto(file: File) { setUploading(true); setMessage(""); const data = new FormData(); data.append("file", file); const res = await fetch("/api/activities/upload", { method: "POST", body: data }); const result = await res.json(); if (res.ok) setPhotoUrl(result.url); else { setPhotoUrl(""); setState("error"); setMessage(result.error || "Upload foto gagal."); } setUploading(false); }
  function removePhoto() { setPhotoUrl(""); }
  async function submit(e: React.FormEvent) {
    e.preventDefault();
    if (lecturers.some(item => !item.name.trim()) || students.some(name => !name.trim())) { setState("error"); setMessage("Lengkapi atau hapus baris dosen dan mahasiswa yang kosong."); return; }
    setState("loading");
    const res = await fetch("/api/activities", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...form, photoUrl, lecturers, students }) });
    const data = await res.json(); setMessage(data.message || data.error); setState(res.ok ? "success" : "error");
  }
  if (state === "success") return <div className="mx-auto max-w-xl px-4 py-20 text-center"><CheckCircle2 className="mx-auto h-14 w-14 text-emerald-600" /><h1 className="mt-5 text-2xl font-bold text-stone-900">Laporan berhasil dikirim</h1><p className="mt-2 text-stone-500">{message}</p><Link href="/" className="mt-7 inline-flex rounded-lg bg-emerald-700 px-5 py-3 text-sm font-semibold text-white">Kembali ke Beranda</Link></div>;
  return <div className="bg-stone-50"><div className="mx-auto max-w-3xl px-4 py-8 sm:py-12"><Link href="/kegiatan" className="mb-6 inline-flex items-center gap-2 text-sm font-medium text-stone-500 hover:text-emerald-700"><ArrowLeft className="h-4 w-4" /> Kembali ke kegiatan</Link><div className="mb-7"><p className="text-xs font-semibold uppercase tracking-wider text-emerald-700">Kontribusi dokumentasi</p><h1 className="mt-2 text-3xl font-bold text-stone-900">Laporkan Kegiatan</h1><p className="mt-2 text-stone-500">Catat kegiatan kolaborasi yang telah dilakukan bersama mitra.</p></div><form onSubmit={submit} className="space-y-6"><Section title="Detail Kegiatan"><div className="grid gap-4 sm:grid-cols-2"><label className="block sm:col-span-2"><span className="mb-1.5 block text-sm font-medium text-stone-700">Mitra *</span><select required value={form.partnerId} onChange={e => set("partnerId", e.target.value)} className="h-11 w-full rounded-lg border border-stone-200 bg-white px-3 text-sm outline-none focus:border-emerald-400"><option value="">Pilih mitra...</option>{partners.map(p => <option key={p.id} value={p.id}>{p.name} ({p.level})</option>)}</select></label><Input label="Nama kegiatan *" required value={form.title} onChange={v => set("title", v)} className="sm:col-span-2" /><Select label="Jenis kegiatan *" value={form.type} onChange={v => set("type", v)} options={[["PENELITIAN","Penelitian"],["PENGABDIAN","Pengabdian"],["MAGANG","Magang"],["KKN","KKN"],["PKL","PKL"],["PERTUKARAN","Pertukaran Mahasiswa"],["PEMBELAJARAN","Pembelajaran"],["SEMINAR","Seminar / Workshop"],["REKRUTMEN","Rekrutmen Lulusan"],["LAINNYA","Lainnya"]]} /><Input label="Tanggal mulai *" type="date" required value={form.dateStart} onChange={v => set("dateStart", v)} /><Input label="Tanggal selesai" type="date" value={form.dateEnd} onChange={v => set("dateEnd", v)} /><Input label="Lokasi" value={form.location} onChange={v => set("location", v)} /><Input label="Unit / Program Studi" value={form.unit} onChange={v => set("unit", v)} /><Input label="Jumlah peserta" type="number" value={form.participants} onChange={v => set("participants", v)} /><TextArea label="Tentang / deskripsi kegiatan" value={form.description} onChange={v => set("description", v)} /><TextArea label="Output kegiatan" value={form.output} onChange={v => set("output", v)} /></div></Section>
    <Section title="Pelaksana Kegiatan"><div className="space-y-4"><div><p className="text-sm font-medium text-stone-700">Dosen yang terlibat *</p><p className="mt-1 text-xs text-stone-400">Pilih satu ketua pelaksana. Dosen lainnya otomatis tercatat sebagai anggota dosen.</p></div>{lecturers.map((item, index) => <div key={index} className="flex items-center gap-2"><input required value={item.name} onChange={e => updateLecturer(index, "name", e.target.value)} placeholder="Nama lengkap dan gelar dosen" className="h-11 min-w-0 flex-1 rounded-lg border border-stone-200 px-3 text-sm outline-none focus:border-emerald-400 focus:ring-2 focus:ring-emerald-100" /><label className="flex shrink-0 items-center gap-1.5 text-xs text-stone-600"><input type="radio" name="lecturerLeader" checked={item.isLeader} onChange={() => updateLecturer(index, "isLeader", true)} className="accent-emerald-700" /> Ketua</label>{lecturers.length > 1 && <button type="button" onClick={() => setLecturers(items => items.filter((_, i) => i !== index))} aria-label="Hapus dosen" className="rounded-lg p-2 text-stone-400 hover:bg-red-50 hover:text-red-600"><Trash2 className="h-4 w-4" /></button>}</div>)}<button type="button" onClick={addLecturer} className="inline-flex items-center gap-1.5 rounded-lg border border-emerald-200 px-3 py-2 text-xs font-semibold text-emerald-700 hover:bg-emerald-50"><Plus className="h-3.5 w-3.5" /> Tambah Dosen</button><div className="border-t border-stone-100 pt-4"><p className="text-sm font-medium text-stone-700">Mahasiswa yang terlibat</p><div className="mt-2 space-y-2">{students.map((name, index) => <div key={index} className="flex items-center gap-2"><input value={name} onChange={e => setStudents(items => items.map((item, i) => i === index ? e.target.value : item))} placeholder="Nama mahasiswa" className="h-11 min-w-0 flex-1 rounded-lg border border-stone-200 px-3 text-sm outline-none focus:border-emerald-400 focus:ring-2 focus:ring-emerald-100" />{students.length > 1 && <button type="button" onClick={() => setStudents(items => items.filter((_, i) => i !== index))} aria-label="Hapus mahasiswa" className="rounded-lg p-2 text-stone-400 hover:bg-red-50 hover:text-red-600"><Trash2 className="h-4 w-4" /></button>}</div>)}</div><button type="button" onClick={addStudent} className="mt-3 inline-flex items-center gap-1.5 rounded-lg border border-stone-200 px-3 py-2 text-xs font-semibold text-stone-600 hover:bg-stone-50"><Plus className="h-3.5 w-3.5" /> Tambah Mahasiswa</button></div></div></Section>
    <Section title="Dokumentasi"><div className="grid gap-4"><label className="block"><span className="mb-1.5 block text-sm font-medium text-stone-700">Foto sampul kegiatan</span><p className="mb-2 text-xs text-stone-400">Foto ini akan ditampilkan sebagai sampul kegiatan di halaman publik. Jika dikosongkan, logo UNEJ akan digunakan otomatis.</p><div className="flex flex-wrap items-start gap-3"><input type="file" accept="image/jpeg,image/png,image/webp" onChange={e => e.target.files?.[0] && uploadPhoto(e.target.files[0])} disabled={uploading || state === "loading"} className="block min-w-0 flex-1 rounded-lg border border-stone-200 bg-white px-3 py-2 text-sm" />{photoUrl && <div className="relative"><img src={photoUrl} alt="Pratinjau foto sampul" className="h-20 w-32 rounded-lg object-cover" /><button type="button" onClick={removePhoto} aria-label="Hapus foto sampul" className="absolute -right-2 -top-2 rounded-full bg-white p-1 text-stone-500 shadow hover:text-red-600"><X className="h-3.5 w-3.5" /></button></div>}</div>{uploading && <p className="mt-2 text-xs text-emerald-700">Mengunggah foto...</p>}</label><Input label="Link Google Drive dokumentasi" type="url" value={form.driveUrl} onChange={v => set("driveUrl", v)} /><Input label="Link publikasi (opsional)" type="url" value={form.publicationUrl} onChange={v => set("publicationUrl", v)} /><p className="text-xs text-stone-400">Pastikan akses link Google Drive dapat dibuka oleh admin.</p></div></Section><Section title="Data Pelapor"><div className="grid gap-4 sm:grid-cols-2"><Input label="Nama pelapor *" required value={form.submittedBy} onChange={v => set("submittedBy", v)} /><Input label="Email" type="email" value={form.submittedEmail} onChange={v => set("submittedEmail", v)} /></div></Section>{state === "error" && <div className="flex items-start gap-2 rounded-lg bg-red-50 p-3 text-sm text-red-700"><AlertCircle className="h-4 w-4" />{message}</div>}<button disabled={state === "loading" || uploading} className="inline-flex items-center gap-2 rounded-xl bg-emerald-700 px-6 py-3.5 text-sm font-semibold text-white hover:bg-emerald-800 disabled:opacity-60"><Send className="h-4 w-4" />{state === "loading" ? "Mengirim..." : "Kirim untuk Verifikasi"}</button></form></div></div>;
}
function Section({ title, children }: { title: string; children: React.ReactNode }) { return <section className="rounded-2xl border border-stone-100 bg-white p-5 shadow-sm sm:p-6"><h2 className="mb-5 flex items-center gap-2 font-bold text-stone-900"><Activity className="h-4 w-4 text-emerald-600" />{title}</h2>{children}</section> }
function Input({ label, value, onChange, type="text", required=false, className="" }: { label: string; value: string; onChange: (v:string)=>void; type?: string; required?: boolean; className?: string }) { return <label className={`block ${className}`}><span className="mb-1.5 block text-sm font-medium text-stone-700">{label}</span><input required={required} type={type} value={value} onChange={e => onChange(e.target.value)} className="h-11 w-full rounded-lg border border-stone-200 px-3 text-sm outline-none focus:border-emerald-400 focus:ring-2 focus:ring-emerald-100" /></label> }
function TextArea({ label, value, onChange }: { label: string; value: string; onChange: (v:string)=>void }) { return <label className="block sm:col-span-2"><span className="mb-1.5 block text-sm font-medium text-stone-700">{label}</span><textarea value={value} onChange={e => onChange(e.target.value)} rows={3} className="w-full rounded-lg border border-stone-200 px-3 py-2.5 text-sm outline-none focus:border-emerald-400 focus:ring-2 focus:ring-emerald-100" /></label> }
function Select({ label, value, onChange, options }: { label: string; value: string; onChange: (v:string)=>void; options: string[][] }) { return <label className="block"><span className="mb-1.5 block text-sm font-medium text-stone-700">{label}</span><select value={value} onChange={e => onChange(e.target.value)} className="h-11 w-full rounded-lg border border-stone-200 bg-white px-3 text-sm outline-none focus:border-emerald-400">{options.map(([v,l]) => <option key={v} value={v}>{l}</option>)}</select></label> }
