"use client";

import { useEffect, useState } from "react";
import { CheckCircle2, ImagePlus, Pencil, Plus, Save, Trash2, X } from "lucide-react";

interface Member { id: string; name: string; isKetua: boolean; phone: string | null; email: string | null; photoUrl: string | null; order: number }
type Form = { name: string; isKetua: boolean; phone: string; email: string; photoUrl: string; order: string };
const EMPTY: Form = { name: "", isKetua: false, phone: "", email: "", photoUrl: "", order: "0" };

export default function TeamAdmin() {
  const [members, setMembers] = useState<Member[]>([]); const [form, setForm] = useState<Form>(EMPTY); const [editing, setEditing] = useState<string | null>(null); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [message, setMessage] = useState("");
  async function load() { const r = await fetch("/api/team"); if (r.ok) setMembers((await r.json()).members); setLoading(false); }
  useEffect(() => { load(); }, []);
  const set = (key: keyof Form, value: string | boolean) => setForm(p => ({ ...p, [key]: value }));
  function startEdit(m: Member) { setEditing(m.id); setForm({ name: m.name, isKetua: m.isKetua, phone: m.phone || "", email: m.email || "", photoUrl: m.photoUrl || "", order: String(m.order) }); setMessage(""); }
  function reset() { setEditing(null); setForm(EMPTY); }
  async function upload(file: File) { const data = new FormData(); data.append("file", file); const r = await fetch("/api/files/upload", { method: "POST", body: data }); const result = await r.json(); if (!r.ok) return setMessage(result.error); set("photoUrl", result.url); }
  async function save(e: React.FormEvent) { e.preventDefault(); setSaving(true); setMessage(""); const r = await fetch(editing ? `/api/team/${editing}` : "/api/team", { method: editing ? "PATCH" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...form, order: Number(form.order) || 0 }) }); const result = await r.json(); if (!r.ok) setMessage(result.error); else { setMessage(editing ? "Data tim diperbarui." : "Anggota tim ditambahkan."); reset(); await load(); } setSaving(false); }
  async function remove(id: string) { if (!confirm("Hapus anggota tim ini?")) return; const r = await fetch(`/api/team/${id}`, { method: "DELETE" }); if (r.ok) load(); }
  return <section className="rounded-2xl border border-stone-100 bg-white p-5 shadow-sm sm:p-6"><div className="flex items-center justify-between"><div><h2 className="text-lg font-bold text-stone-900">Tim Kerja Sama Prodi</h2><p className="mt-1 text-sm text-stone-500">Kelola nama, jabatan, kontak, dan foto anggota tim.</p></div>{editing === null && <button onClick={() => setMessage("")} className="inline-flex items-center gap-1.5 rounded-lg bg-emerald-700 px-3 py-2 text-xs font-semibold text-white"><Plus className="h-3.5 w-3.5" /> Tambah Anggota</button>}</div>
    <form onSubmit={save} className="mt-5 grid gap-4 rounded-xl bg-stone-50 p-4 sm:grid-cols-2">
      <label className="block sm:col-span-2"><span className="mb-1.5 block text-sm font-medium text-stone-700">Nama lengkap dan gelar *</span><input required value={form.name} onChange={e => set("name", e.target.value)} placeholder="Contoh: Dr. Nama Lengkap, S.TP., M.Si." className="h-11 w-full rounded-lg border border-stone-200 bg-white px-3 text-sm" /></label>
      <label className="flex items-center gap-2 text-sm font-medium text-stone-700"><input type="checkbox" checked={form.isKetua} onChange={e => set("isKetua", e.target.checked)} className="h-4 w-4 accent-emerald-600" /> Ketua Tim Kerja Sama Prodi</label>
      <label><span className="mb-1.5 block text-sm font-medium text-stone-700">Urutan tampil</span><input type="number" min="0" value={form.order} onChange={e => set("order", e.target.value)} className="h-11 w-full rounded-lg border border-stone-200 bg-white px-3 text-sm" /></label>
      <label><span className="mb-1.5 block text-sm font-medium text-stone-700">Nomor telepon</span><input value={form.phone} onChange={e => set("phone", e.target.value)} className="h-11 w-full rounded-lg border border-stone-200 bg-white px-3 text-sm" /></label>
      <label><span className="mb-1.5 block text-sm font-medium text-stone-700">Email</span><input type="email" value={form.email} onChange={e => set("email", e.target.value)} className="h-11 w-full rounded-lg border border-stone-200 bg-white px-3 text-sm" /></label>
      <label className="sm:col-span-2"><span className="mb-1.5 block text-sm font-medium text-stone-700">Foto (JPG, PNG, WEBP — maksimal 5 MB)</span><div className="flex items-center gap-3"><input type="file" accept="image/jpeg,image/png,image/webp" onChange={e => e.target.files?.[0] && upload(e.target.files[0])} className="block w-full rounded-lg border border-stone-200 bg-white px-3 py-2 text-sm" />{form.photoUrl && <img src={form.photoUrl} alt="Preview" className="h-12 w-12 rounded-lg object-cover" />}</div></label>
      {message && <p className="text-sm text-emerald-700 sm:col-span-2">{message}</p>}
      <div className="flex gap-2 sm:col-span-2"><button disabled={saving} className="inline-flex items-center gap-1.5 rounded-lg bg-emerald-700 px-4 py-2.5 text-xs font-semibold text-white disabled:opacity-60"><Save className="h-3.5 w-3.5" /> {saving ? "Menyimpan..." : editing ? "Simpan Perubahan" : "Simpan Anggota"}</button>{editing && <button type="button" onClick={reset} className="inline-flex items-center gap-1.5 rounded-lg border border-stone-200 px-4 py-2.5 text-xs font-semibold text-stone-600"><X className="h-3.5 w-3.5" /> Batal</button>}</div>
    </form>
    {loading ? <p className="mt-5 text-sm text-stone-400">Memuat...</p> : members.length === 0 ? <p className="mt-5 rounded-xl border border-dashed border-stone-200 p-6 text-center text-sm text-stone-400">Belum ada anggota tim.</p> : <div className="mt-5 divide-y divide-stone-100">{members.map(m => <div key={m.id} className="flex items-center gap-3 py-3"><div className="h-12 w-12 shrink-0 overflow-hidden rounded-xl bg-emerald-50 text-center text-sm font-bold leading-[3rem] text-emerald-700">{m.photoUrl ? <img src={m.photoUrl} alt={m.name} className="h-full w-full object-cover" /> : m.name.split(/\s+/).slice(0, 2).map(x => x[0]).join("")}</div><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold text-stone-800">{m.name}</p><p className="text-xs text-emerald-700">{m.isKetua ? "Ketua Tim Kerja Sama Prodi" : "Anggota Tim Kerja Sama Prodi"}</p></div><button onClick={() => startEdit(m)} className="rounded-lg p-2 text-stone-400 hover:bg-stone-50 hover:text-emerald-700" aria-label="Edit"><Pencil className="h-4 w-4" /></button><button onClick={() => remove(m.id)} className="rounded-lg p-2 text-stone-400 hover:bg-red-50 hover:text-red-600" aria-label="Hapus"><Trash2 className="h-4 w-4" /></button></div>)}</div>}
  </section>;
}
